### ISSUE TITLE
Builds were failing for 3+ months

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-portable#21]
This means that [r-appveyor](https://github.com/krlmlr/r-appveyor) was using the same version of R-devel since January 7, 2015, although it's supposed to be using bleeding-edge R-devel updated daily. I have now updated the images. As a consequence, tests that used to work might now fail. My sincere apologies for that.

---

CC r-appveyor users: @ropensci @Reproducible-Science-Curriculum @GotelliLab @richfitz @sckott @rOpenGov @GuangchuangYu @gaborcsardi @bcohn @USGS-R @shtumpa @fawda123 @jrklasen @zhengxwen @kerschke @leeper @dfci-cccb @tudo-r @scrm @jimhester @GLEON @paulstaab @metacran @Melinae @LiveOak @OuhscBbmc @c5sire @HenrikBengtsson @qinwf @lbraglia @NREL @fmichonneau @gavinsimpson @berndbischl @karawoo @keyuan @jhollist @surmann @vegandevs @Przemol @mllg @bwtian @hadley @jread-usgs

**Comment by HenrikBengtsson** [comment]
Thanks for providing and maintaining this.  It's a really valuable resource and much appreciated.

**Comment by gaborcsardi** [comment]
Agree with @HenrikBengtsson completely! 

Some lagging is no big deal, it is probably still fresher than R-release, and it still worked fine for most people, otherwise we have had been complaining.

**Comment by jread-usgs** [comment]
double thumbs up from us at USGS-R too.

**Comment by paulstaab** [comment]
No harm done for my projects. Thanks for fantastic work here!

**Comment by sckott** [comment]
I think all mine are fine, thanks @krlmlr !

**Comment by surmann** [comment]
Mine is fine, too. Thanks @krlmlr !

**Comment by krlmlr** [comment]
Everything seems stable now.

**Comment by krlmlr** [comment]
Builds started to fail again just two days after my previous comment (as of July 3). I'm sorry -- I missed that single build failure notification message.

Now I have set up a notification for each failing build (e10fc2a686a8421a081695246f7064521f378ba5), let's hope for the best.

**Comment by gaborcsardi** [comment]
No worries, it's ok if a couple of builds fail.....
